### ISSUE TITLE
'Open Folder' does not work

### ISSUE THREAD

**Issue by Steve0x43** [apollographql/apollo-workbench-vscode#168]
The 'Open Folder' button does not appear to work. The macOS dialog displays to select a directory, but after selecting a directory it does not appear to have been opened.

<img width="458" alt="image" src="https://github.com/apollographql/apollo-workbench-vscode/assets/166616/e1c6e4f1-8866-4577-a9c4-41c150877570">

Apollo Workbench VSCode 3.2.10 (and previous versions)
macOS Sonoma 14.0

I managed to find a relevant entry in the VS Code logs:

```
2023-11-03 10:03:05.726 [error] command 'openFolder' not found: Error: command 'openFolder' not found
    at y.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1537:12331)
    at y.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1537:12260)
```

**Comment by michael-watson** [comment]
I just released 3.2.11 with a fix for this, thanks for reporting!
